Repository WPI-MMR/gym_solo, pull requests merged in 2020-11, with the labels that each got.

#12 Create Torso Upright Reward
  gym_solo/core/rewards.py
  gym_solo/core/test_rewards_factory.py
Labels: new feature

#26 Update CI to Support Python 3.7
  .github/workflows/python-test-coverage.yml
Labels: cleanliness

#27 Termination factory and Time based termination condition
  gym_solo/core/termination.py
  gym_solo/core/test_termination_conditions.py
  gym_solo/core/test_termination_factory.py
  gym_solo/envs/solo8v2vanilla.py
Labels: cleanliness, new feature
